// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVfDkajTZeBK11enR74eDrPi2vuwSMvvw',
    appId: '1:58916145091:web:1df97af741d1dcd5875f76',
    messagingSenderId: '58916145091',
    projectId: 'room-booking-3e0aa',
    authDomain: 'room-booking-3e0aa.firebaseapp.com',
    storageBucket: 'room-booking-3e0aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6-DfPXr-o56k97WYfVODioi4ZwFmbMQg',
    appId: '1:58916145091:android:7b509cce6c2d04e8875f76',
    messagingSenderId: '58916145091',
    projectId: 'room-booking-3e0aa',
    storageBucket: 'room-booking-3e0aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZjOSa6kzJp8PVtlIsHMPNq4adroOlUzM',
    appId: '1:58916145091:ios:fd0c345e414237e7875f76',
    messagingSenderId: '58916145091',
    projectId: 'room-booking-3e0aa',
    storageBucket: 'room-booking-3e0aa.firebasestorage.app',
    iosBundleId: 'com.example.meetingSpaceBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZjOSa6kzJp8PVtlIsHMPNq4adroOlUzM',
    appId: '1:58916145091:ios:fd0c345e414237e7875f76',
    messagingSenderId: '58916145091',
    projectId: 'room-booking-3e0aa',
    storageBucket: 'room-booking-3e0aa.firebasestorage.app',
    iosBundleId: 'com.example.meetingSpaceBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVfDkajTZeBK11enR74eDrPi2vuwSMvvw',
    appId: '1:58916145091:web:ee79ff2a8f3a00f4875f76',
    messagingSenderId: '58916145091',
    projectId: 'room-booking-3e0aa',
    authDomain: 'room-booking-3e0aa.firebaseapp.com',
    storageBucket: 'room-booking-3e0aa.firebasestorage.app',
  );
}
